### ISSUE TITLE
Bomb implementation

### ISSUE THREAD

**Issue by ayalan** [avcdsld/pepe-crush#1]
### Bomb charms
Bomb charms are the same as the regular charm, but they only appear after clearing 4+ in a match, and when used in a match, they will clear all charms of that type from the board.

### Appearance
Alternate between the tile and tile+16 to create flashing effect. Example: Tile 1 and Tile 17 should quickly infinitely loop.
![bomb-example](https://user-images.githubusercontent.com/1248159/187807299-9fcdd68e-9036-4296-8b22-9aaf02ae7f35.gif)

### Gameplay: How Bombs are Made
- If the player clears 4 or more charms at once, then one existing charm of that type will become a bomb of that type. If no other charms of that type exist, add it to board from the top. 
- Example 1: User clears a row of 5 🐸. There are no other 🐸 on the board. From the top, a bomb 🐸 will appear.
- Example 2: User clears a row of 4 Mirrors. There are 5 other Mirrors on the board. One of the existing Mirrors will transform into a bomb Mirror.

### Gameplay: How Bombs are Used
- If the user clears a set of charms that includes a bomb charm (such as as with 2 regular :scissors: and 1 bomb :scissors:), then ALL remaining :scissors: on the board will disappear.
- When remaining charms are destroyed, it does not add more time. Only clearing from matches of 3+ will add time.
- Charms cleared as a result of bomb do not contribute additional time to the timer.
- Example: A match of 2 regular :scissors: and 1 bomb :scissors: happens. 5 seconds are added to the timer. As a result of the bomb, 12 more :scissors: are cleared from the board. 

### Scoring
- When bombs are used, the scoring uses the same logic as any other match (count * count) for matched set.
- Additional charms which are destroyed as a result of using the bomb are also counted and scored using the (count * count) rule.
- Example: There are 15 total scissors on the board. A match of 3 :scissors: occurs (and one of them is :scissors: bomb). +9 points for the match of 3, and clear them. There are 12 :scissors: left on the board, and they are also then cleared because bomb was used. Additional +144 points.

**Comment by avcdsld** [comment]
I close this once. We will reopen if something happens.
