### ISSUE TITLE
Potential bug: When lined up vertically and horizontally at the same time, only the horizontal is cleared.

### ISSUE THREAD

**Issue by avcdsld** [avcdsld/pepe-crush#11]

**Comment by ayalan** [comment]
Agree, I think that if a match is valid in multiple directions, then both should clear. 

Example:
✂️🐸💧✂️
🥕🐸✂️💧   
💧 🍒🐸🐸 
🥕🐸🥕💧 

Swapping the lowest 🐸 with 🍒 should cause both the horizontal and vertical matches to clear.
The scores would be (3 * 3) + (3 * 3).
This should not cause a bomb to form.

(The user also has a potential to make a single vertical match of 4 here, but I'm ignoring that possibility for this example.)
