### ISSUE TITLE
Game had no more valid moves, but game did not end if last move was bomb creation

### ISSUE THREAD

**Issue by ayalan** [avcdsld/pepe-crush#18]
It seems that this happens in this specific scenario:

1. There is only 1 valid move left: to match a row of 4.
2. Row of 4 is matched, and a bomb is made.
3. There are no more valid moves.
4. Game does not end.

I think this only occurs if the last remaining move was creating a bomb. Perhaps the check for if valid moves exists is not triggered when the bomb is made?

**Comment by ayalan** [comment]
https://user-images.githubusercontent.com/1248159/188390939-6ab363a3-442d-4ebf-b674-4ad7542660c4.mp4

**Comment by avcdsld** [comment]
Sorry for the trouble.
I checked and the bomb generation probably had nothing to do with it, it was simply not checked enough. It should be fixed with this PR:
https://github.com/avcdsld/pepe-crush/pull/20

**Comment by ayalan** [comment]
I see, thank you for checking! I will confirm it tomorrow ✨
