### ISSUE TITLE
Game ended for unknown reason

### ISSUE THREAD

**Issue by ayalan** [avcdsld/pepe-crush#19]
There are still at least two more moves remaining.
There is still lots of time left.

Game ended anyways. 

https://user-images.githubusercontent.com/1248159/188393736-00b2d6f7-7b21-4e45-87e4-1774ac459b82.mp4

**Comment by avcdsld** [comment]
Thanks for reporting the bug. It should be fixed with this PR:
https://github.com/avcdsld/pepe-crush/pull/20
