### ISSUE TITLE
Add score share flow

### ISSUE THREAD

**Issue by ayalan** [avcdsld/pepe-crush#6]
When the game is over, the user has an option to Play Again, or Share. 
If the user selects Share, a new screen is drawn.

This screen includes a QR code, and the text: "Scan to share your score on Twitter!"

The QR code will create a Tweet with the text: "I just scored {score} on #HAIRPEPESuperShine"

**Comment by avcdsld** [comment]
@ayalan Do you know anything about how to generate a QR code in Pico-8?

**Comment by ayalan** [comment]
Someone apparently made some code that will do it during a Game Jam event several years ago.
https://github.com/ctinney94/Pico8-QR-Code-Generator
https://itch.io/jam/procjam2019/rate/514330

If we want to make dynamic content for the tweet text so that the score is included, then we would need something like this.

**Comment by ayalan** [comment]
https://github.com/speedata/luaqrcode

**Comment by ayalan** [comment]
<img width="675" alt="Screen Shot 2022-09-15 at 13 50 25" src="https://user-images.githubusercontent.com/1248159/190317466-83fc9021-29b9-4294-af37-7b05fbd9c451.png">
